### ISSUE TITLE
Authentification des utilisateur

### ISSUE THREAD

**Issue by StyveLioumba** [essengogroup/dashboard-touri#1]
- [x] Login
- [x] Register

**Comment by StyveLioumba** [comment]
l'inscription et connexion fonctionne , il ne reste qu'a designer les pages pour terminer #1 
@milandou  quand tu as du temps essaie de voir le projet

si quelqu'un fait le design , elle doit d'abord créer une branch 

`git checkout -b feature/#1`

le #1 dans la ligne de commande est le tag de l'issue sur git.

les commits commenceront par #1 blablabla
ex : 
`git commit -m "#1 signIn page is finish"`

puis 

`git push origin feature/#1`

pour pousser les modifs apportés

pensez a faire une pull request ensuite

**Comment by milandou** [comment]
on a toujours l'ancien design de la derniere version que nous avons fait ressement?

**Comment by StyveLioumba** [comment]
j'en ai plus.
